markdown: GFM
theme: just-the-docs
color_scheme: dark
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
title: Wirtschaftslehre im StudienKolleg